services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: dev
        container_name: app-mmo
        volumes: &volumes
            - public-volume:/var/www/public
            - ./.env:/var/www/.env
            - ./.env.local:/var/www/.env.local
            - ./.env.test:/var/www/.env.test
            - ./composer.json:/var/www/composer.json
            - ./composer.lock:/var/www/composer.lock
            - ./symfony.lock:/var/www/symfony.lock
            - ./bin:/var/www/bin
            - ./config:/var/www/config
            - ./src:/var/www/src
            - ./tests:/var/www/tests
            - ./.php-cs-fixer.dist.php:/var/www/.php-cs-fixer.dist.php
            - ./phpstan.neon.dist:/var/www/phpstan.neon.dist
            - ./docker/phpstan:/var/www/docker/phpstan
            - ./psalm.xml:/var/www/psalm.xml
            - ./docker/psalm:/var/www/docker/psalm
        networks:
            - dev-network

    nginx:
        image: nginx:alpine
        container_name: nginx-mmo
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - public-volume:/var/www/public
        ports:
            - "80:80"
        networks:
            - dev-network
        depends_on:
            - app

networks:
    dev-network:
        driver: bridge

volumes:
    public-volume:
