services:

    nginx:
        image: nginx:alpine
        container_name: nginx-mmo
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public
        ports:
            - "80:80"
        networks:
            - network
        depends_on:
            - app


    mysql:
        image: mysql:8.0
        container_name: mysql-mmo
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_CHARACTER_SET_SERVER: utf8mb4
            MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --skip-character-set-client-handshake
            --pid-file=/var/lib/mysql/mysqld.pid
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - network


####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-16}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    healthcheck:
#      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###

networks:
    network:
        driver: bridge

volumes:
    public-volume:
        name: mmo_public_dir
    mysql-data:
        name: mmo_mysql_data

####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###
