#   bin/console debug:router

api_routes:
    resource: 'routes/routes_api.yaml'
    prefix: /api
    defaults:
        _format: json

admin_routes:
    resource: 'routes/routes_admin.yaml'
    prefix: /admin

controllers:
    resource: routing.controllers

homepage:
    path: /
    controller: App\Controller\UserController::showTestAction
    methods: ['GET']

user_registration_page:
    path: /registration
    controller: App\Controller\UserController::showRegistrationAction
    methods: ['GET']


user_clear_table:
    path: /CLEAR
    controller: App\Controller\TableClearController::clearUserEntityTable
    methods: ['POST']












