services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller/**'
        tags: [ 'controller.service_arguments' ]

    App\Resolver\ArgumentValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }

    App\Subscriber\ResponseExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'


